- name: packages pinning
  template: >
    src=pinning.j2
    dest=/etc/apt/preferences.d/haproxy
  sudo: yes

- name: repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - deb http://cdn.debian.net/debian {{ ansible_distribution_release }}-backports main
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - haproxy
  sudo: yes